### ISSUE TITLE
Joycond cannot find my joycon after bluetooth connected.

### ISSUE THREAD

**Issue by DasCrystal** [DanielOgorchock/joycond#138]
My system is Fedora 39 Workstation (Kernel Version: 6.6.8-200.fc39.x86_64), with conditions below:

- Kernel Module "hid_nx" is installed
![image](https://github.com/DanielOgorchock/joycond/assets/78836480/8bfeeb64-7d11-4207-9a3e-d94e6740c094)
- "joycond" install and enabled
![image](https://github.com/DanielOgorchock/joycond/assets/78836480/60a97208-8fd9-4083-b735-d2d21d25821d)
- Joycon connected
![image](https://github.com/DanielOgorchock/joycond/assets/78836480/30f7be20-39fc-4e7c-8562-fa6cf7bcdab3)

But joycon didn't vibrate, the led on it not changed. Couldn't see in the yuzu, either.
(It's works good on windows (on same computer) with BetterJoy, so it shouldn't be a hardware problem.)

And in joycond service, it just stuck at "adding epoll_subscriber: fd=4", no further react.

If you need more information, please tell me.

EDIT: With state above, the connection with joycon will keep about 10 to 30 seconds, then disconnect, due to the automatic power off of joycon.

**Comment by Beethoven-n** [comment]
same here on arch, kernel 6.7.1

**Comment by erudic** [comment]
Hello,

Are lights on your joycon moving from left to right? If yes, then you might be able to resolve the problem same way I did by following steps from this comment: https://github.com/bluez/bluez/issues/673#issuecomment-1849132576

**Comment by DasCrystal** [comment]
First, thanks to @erudic for providing a great approch for this issue.
although that way isn't working for me, but int the same issue page, I found a resolution below:

Set these configs: (sudo vi or something else, and save them)
"UserspaceHID=true", in "/etc/bluetooth/input.conf"
"ClassicBondedOnly=false", also in "/etc/bluetooth/input.conf"
"FastConnectable = true" in "/etc/bluetooth/main.conf"

Then reboot.

And you might found your Joy-Con Works again!
This worked for me.
