### ISSUE TITLE
cmake version change

### ISSUE THREAD

**Issue by mroduner** [DanielOgorchock/joycond#18]
I was trying to build this on raspbian, and  got an error asking for cmake 3.14 (as it should, per the makefile); but it doesn't appear to actually require any features that are not present in 3.13 (still the default in a lot of things).  

After a quick edit to the CMakeLists.txt to change the version; everything built and worked fine... unless I'm missing something, it seems that changing the version would allow for people to use this that might be comfortable with git, but not into actually editing source.

**Comment by joaorb64** [comment]
Same here for Ubuntu 19.10.

**Comment by DanielOgorchock** [comment]
Thanks, fixed.
