### ISSUE TITLE
Can't get it to work.

### ISSUE THREAD

**Issue by Bonicgamer** [DanielOgorchock/joycond#19]
When I connect my Joycons to my computer and press the L & R buttons nothing happens.
I looked and saw it might be trying to look in an invalid directory. When I ran _journalctl_ it   showed: 
> no match found for /sys//devices/_(eccetera)_

So if I'm doing something wrong please tell me.

**Comment by parkerlreed** [comment]
Do you have the kernel module?

**Comment by Bonicgamer** [comment]
> Do you have the kernel module?

Yes, I got it from the AUR, so I might try to install it manually sometime later today to see if that somehow fixes it.

**Comment by Bonicgamer** [comment]
>so I might try to install it manually sometime later today to see if that somehow fixes it.

Well it somehow fixed it.

**Comment by Magicrafter13** [comment]
> Do you have the kernel module?

There's a kernel module??
