### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by PowerUser64** [DanielOgorchock/joycond#25]
I have done a bit of research, but is unclear how to uninstall this. When I installed it, I followed the instructions in the readme.

**Comment by greasysock** [comment]
What I am assuming is, you need to reverse the install steps found in this file: [CMakeLists.txt](../blob/master/CMakeLists.txt), but you need to stop and disable the daemon first. There currently is no uninstall target.

**Comment by PowerUser64** [comment]
Alright, sounds good. Thanks!

**Comment by PowerUser64** [comment]
Just figured out you can install and uninstall from the AUR and that will remove it

**Comment by benhriv** [comment]
> What I am assuming is you need to reverse the install steps found in this file: [CMakeLists.txt](../blob/master/CMakeLists.txt), but you need to stop and disable the daemon first. There currently is no uninstall target.

Sorry, I don't understand. How do you do this?

**Comment by subtlecobra3864** [comment]
> What I am assuming is you need to reverse the install steps found in this file: [CMakeLists.txt](../blob/master/CMakeLists.txt), but you need to stop and disable the daemon first. There currently is no uninstall target.

Can you explain this a bit further?

**Comment by PowerUser64** [comment]
If you look at the bottom of the file where the lines that read `install()` are, you can delete manually delete the files listed.
[Example:](https://github.com/DanielOgorchock/joycond/blob/master/CMakeLists.txt#L28)
```cmake
install(FILES systemd/joycond.service DESTINATION /etc/systemd/system)
```
means you remove the file `joycond.service` at `/etc/systemd/system`, like this:
```bash
rm /etc/systemd/system/joycond.service
```
and then you can repeat that for all the other

**Comment by cr1za** [comment]
> Just figured out you can install and uninstall from the AUR and that will remove it

What is AUR?
