### ISSUE TITLE
cmake issue

### ISSUE THREAD

**Issue by Mumrik93** [DanielOgorchock/joycond#29]
I received an error while applying the "cmake ." command. I received the following message (full log attached); 
"
-- Checking for module 'libevdev'
--   No package 'libevdev' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  CMakeLists.txt:10 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/mumrik/joycond/CMakeFiles/CMakeOutput.log".
"
[CMakeOutput.log](https://github.com/DanielOgorchock/joycond/files/5138013/CMakeOutput.log)

**Comment by DanielOgorchock** [comment]
You need to install libevdev. Depending on your distribution, make sure you install the development package so that the header is installed.
